// // Browser Extension - Magic Actions - CHROMEACTIONS.COM - Copyright (c) 2023 Mixesoft - All Rights Reserved
// Minified by Google Closure Compiler 20240317
try{const c=window,p={},r=function(){c.location.href="https://www.chromeactions.com/";return[null,null]},w=function(){var a=c.location.hash;c.history.replaceState(null,"",location.origin);if(a){c.location.hash="";a=a.slice(1).split("-");let b=parseInt(a[0])-Date.now(),l=parseInt(a[1]);a=parseInt(a[2]);return 2330>b?[l,a]:r()}return r()},[m,q]="data:"==c.location.protocol?JSON.parse("ARGS"):w(),t=function(a){a instanceof Event&&a.isTrusted&&(a.preventDefault(),a.stopPropagation(),a.stopImmediatePropagation())},
f=function(a,b){return Math.floor(Math.random()*(b+1-a))+a},u=function(){c.outerWidth==p.w&&c.outerHeight==p.h||c.resizeTo(p.w,p.h);setTimeout(u,2E3)},x=function(){var a=10<m?m-10:m,b=2==a||5==a||8==a,l=4==a||5==a||6==a,g=f(1,54),h=c.screen.availWidth,k=c.screen.availHeight,n=p.w=c.outerWidth,d=p.h=c.outerHeight;b=b?parseInt((h-n-g)/2,10):1==a||4==a||7==a?g:h-n-g;a=l?parseInt((k-d-g)/2,10):1==a||2==a||3==a?g:k-d-g;n>h&&(b=0);d>k&&(a=0);1>b&&(b=0);1>a&&(a=0);c.moveTo(b,a);setTimeout(u,2E3)},y=function(a){let b=
f(0,1),l=f(0,359),g=f(0,21),h=f(13,55),k=f(1,21),n=f(21,55),d=f(89,100),e="hsl(0deg 0% "+d+"%)";a=a.sheet;a.cssRules[1].style.background="hsl("+l+"deg "+h+"% "+d+"%)";a.cssRules[1].style.color="hsl(0deg 0% "+k+"%)";a.cssRules[7].cssRules[0].style.background="hsl("+l+"deg "+h+"% "+k+"%)";a.cssRules[7].cssRules[0].style.color=e;a.cssRules[6].style.color=e;a.cssRules[6].style.background="hsl("+(b?f(350,360):f(210,220))+"deg,79%,"+f(34,55)+"%)";return["hsl("+g+"deg "+h+"% "+n+"%)",e]},z=function(){return"https://www.chromeactions.com/"+
["clear-browsing-data","browser-update-checker","secure-your-google-account"][q-3]+".html"},C=function(a){if(a instanceof Event&&a.isTrusted){let l=(chrome&&chrome.i18n&&chrome.i18n.getMessage("msg"+q)||"I18N").split(";"),g=document.createDocumentFragment(),h=document.createElement("main"),k=document.createElement("div"),n=document.createElement("h4"),d=document.createElement("a");let e,v=document.body.attachShadow({mode:"closed"});var b=document.querySelector('[rel="stylesheet"]')||document.querySelector("style");
v.appendChild(b);const [A,B]=y(b);b=document.createElementNS("http://www.w3.org/2000/svg","svg");b.setAttributeNS(null,"viewBox","0 0 16 16");e=document.createElementNS("http://www.w3.org/2000/svg","path");e.setAttributeNS(null,"fill",A);e.setAttributeNS(null,"d","M8 0a.67.67.0 00-.25.05L1.4 2.59c-.24.1-.4.33-.4.58v3.09c0 4.26 2.67 8.09 6.76 9.7.15.06.33.06.48.0A10.47 10.47.0 0015 6.25v-3.1a.63.63.0 00-.4-.57L8.25.05A.67.67.0 008 0z");b.appendChild(e);e=document.createElementNS("http://www.w3.org/2000/svg",
"path");e.setAttributeNS(null,"fill",B);e.setAttributeNS(null,"d","M8 4.29A1.75 1.75.0 006.25 6.04 1.75 1.75.0 108 4.29zm.06 4.17a3.73 3.73.0 00-3.54 2.39 4.5 4.5.0 006.96.0 3.73 3.73.0 00-3.42-2.4z");b.appendChild(e);n.textContent=l[0];d.href=z();d.target="_blank";d.rel="noopener";d.textContent=l[1];d.setAttribute("autofocus","");k.appendChild(b);k.appendChild(n);h.appendChild(k);h.appendChild(d);g.appendChild(h);v.appendChild(g);a.stopPropagation();a.stopImmediatePropagation()}};"number"==typeof m&&
"number"==typeof q&&-1<m&&20>m&&-1<q&&6>q?(0!=m&&10!=m&&x(),2<q&&c.addEventListener("load",C,!0),c.addEventListener("contextmenu",t,!0),c.addEventListener("click",function(a){if(a instanceof Event&&a.isTrusted){let b=a.target;"body"!=b.localName&&("a"==b.localName&&b.href.startsWith("https://www.chromeactions.com/")?c.close():t(a))}},!0)):r();setTimeout(function(){c.close()},105E5)}catch(c){console.info(c)};
